import type { Metadata } from 'next'
import { Toaster } from 'react-hot-toast'
import './globals.css'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang='en'>
			<body>
				<Toaster />
				<div className='bg-gray-50 w-screen h-screen'>
					<div className='max-w-md pt-20 mx-auto'>{children}</div>
				</div>
			</body>
		</html>
	)
}
